
name: Job AI Agent (Daily)

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch: {}

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare config
        run: |
          if [ ! -f config/config.yaml ]; then cp config/config.example.yaml config/config.yaml; fi

      - name: Run agent
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          REPORT_TO_EMAIL: ${{ secrets.REPORT_TO_EMAIL }}
          REPORT_FROM_EMAIL: ${{ secrets.REPORT_FROM_EMAIL }}
        run: |
          # Use module form to avoid import-path issues
          python -m agent --config config/config.yaml

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: job-report
          path: reports/latest_report.html
